export default {

  //LOCAL
  BASE_URl: "https://YOUR_API_BASE_URL/",

  PUBLISH_KEY: "YOUR_STRIPE_PUBLISHABLE_KEY",

  VEIFY_IDENTITY_TEMPLATE_ID: "YOUR_VERIFY_IDENTITY_TEMPLATE_ID",

  //Changes to Live url when done
  RESERVE_URL: "https://YOUR_API_BASE_URL/authentication/login",

  // Sample integration tokens (provide via secure config in real deployments)
  PLACES_API_TOKEN: "YOUR_PLACES_API_TOKEN",
  DIRECTIONS_API_TOKEN: "YOUR_DIRECTIONS_API_TOKEN",

  NEW_SIGNUP_REQUEST: "NEW_SIGNUP_REQUEST",
  NEW_SIGNUP_SUCCESS: "NEW_SIGNUP_SUCCESS",
  NEW_SIGNUP_FAILURE: "NEW_SIGNUP_FAILURE",

  SIGNIN_REQUEST: "SIGNIN_REQUEST",
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNIN_FAILURE: "SIGNIN_FAILURE",

  FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAILURE: "FORGOT_PASSWORD_FAILURE",

  MOBILE_VERIFICATION_REQUEST: "MOBILE_VERIFICATION_REQUEST",
  MOBILE_VERIFICATION_SUCCESS: "MOBILE_VERIFICATION_SUCCESS",
  MOBILE_VERIFICATION_FAILURE: "MOBILE_VERIFICATION_FAILURE",

  RESEND_OTP_REQUEST: "RESEND_OTP_REQUEST",
  RESEND_OTP_SUCCESS: "RESEND_OTP_SUCCESS",
  RESEND_OTP_FAILURE: "RESEND_OTP_FAILURE",

  GET_COUNTRIES_REQUEST: "GET_COUNTRIES_REQUEST",
  GET_COUNTRIES_SUCCESS: "GET_COUNTRIES_SUCCESS",
  GET_COUNTRIES_FAILURE: "GET_COUNTRIES_FAILURE",

  CAR_BRAND_REQUEST: "CAR_BRAND_REQUEST",
  CAR_BRAND_SUCCESS: "CAR_BRAND_SUCCESS",
  CAR_BRAND_FAILURE: "CAR_BRAND_FAILURE",

  CAR_TYPE_REQUEST: "CAR_TYPE_REQUEST",
  CAR_TYPE_SUCCESS: "CAR_TYPE_SUCCESS",
  CAR_TYPE_FAILURE: "CAR_TYPE_FAILURE",

  CAR_IMAGES_REQUEST: "CAR_IMAGES_REQUEST",
  CAR_IMAGES_SUCCESS: "CAR_IMAGES_SUCCESS",
  CAR_IMAGES_FAILURE: "CAR_IMAGES_FAILURE",

  GENERAL_SETTINGS_REQUEST: "GENERAL_SETTINGS_REQUEST",
  GENERAL_SETTINGS_SUCCESS: "GENERAL_SETTINGS_SUCCESS",
  GENERAL_SETTINGS_FAILURE: "GENERAL_SETTINGS_FAILURE",

  BECOME_DRIVER_REQUEST: "BECOME_DRIVER_REQUEST",
  BECOME_DRIVER_SUCCESS: "BECOME_DRIVER_SUCCESS",
  BECOME_DRIVER_FAILURE: "BECOME_DRIVER_FAILURE",

  CHANGE_PASSWORD_REQUEST: "CHANGE_PASSWORD_REQUEST",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAILURE: "CHANGE_PASSWORD_FAILURE",

  ADD_PROFILE_PICTURE_REQUEST: "ADD_PROFILE_PICTURE_REQUEST",
  ADD_PROFILE_PICTURE_SUCCESS: "ADD_PROFILE_PICTURE_SUCCESS",
  ADD_PROFILE_PICTURE_FAILURE: "ADD_PROFILE_PICTURE_FAILURE",

  EDIT_PROFILE_REQUEST: "EDIT_PROFILE_REQUEST",
  EDIT_PROFILE_SUCCESS: "EDIT_PROFILE_SUCCESS",
  EDIT_PROFILE_FAILURE: "EDIT_PROFILE_FAILURE",

  USER_DETAILS_REQUEST: "USER_DETAILS_REQUEST",
  USER_DETAILS_SUCCESS: "USER_DETAILS_SUCCESS",
  USER_DETAILS_FAILURE: "USER_DETAILS_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  TERMS_OF_SERVICE_REQUEST: "TERMS_OF_SERVICE_REQUEST",
  TERMS_OF_SERVICE_SUCCESS: "TERMS_OF_SERVICE_SUCCESS",
  TERMS_OF_SERVICE_FAILURE: "TERMS_OF_SERVICE_FAILURE",

  CHECK_SOCIAL_ID_REQUEST: "CHECK_SOCIAL_ID_REQUEST",
  CHECK_SOCIAL_ID_SUCCESS: "CHECK_SOCIAL_ID_SUCCESS",
  CHECK_SOCIAL_ID_FAILURE: "CHECK_SOCIAL_ID_FAILURE",

  INTERCITY_SEARCH_REQUEST: "INTERCITY_SEARCH_REQUEST",
  INTERCITY_SEARCH_SUCCESS: "INTERCITY_SEARCH_SUCCESS",
  INTERCITY_SEARCH_FAILURE: "INTERCITY_SEARCH_FAILURE",

  CITY_SEARCH_REQUEST: "CITY_SEARCH_REQUEST",
  CITY_SEARCH_SUCCESS: "CITY_SEARCH_SUCCESS",
  CITY_SEARCH_FAILURE: "CITY_SEARCH_FAILURE",

  PLACE_SEARCH_REQUEST: "PLACE_SEARCH_REQUEST",
  PLACE_SEARCH_SUCCESS: "PLACE_SEARCH_SUCCESS",
  PLACE_SEARCH_FAILURE: "PLACE_SEARCH_FAILURE",

  PICKUP_CITY_SEARCH_REQUEST: "PICKUP_CITY_SEARCH_REQUEST",
  PICKUP_CITY_SEARCH_SUCCESS: "PICKUP_CITY_SEARCH_SUCCESS",
  PICKUP_CITY_SEARCH_FAILURE: "PICKUP_CITY_SEARCH_FAILURE",

  INTERCITY_MY_BOOKINGS_REQUEST: "INTERCITY_MY_BOOKINGS_REQUEST",
  INTERCITY_MY_BOOKINGS_SUCCESS: "INTERCITY_MY_BOOKINGS_SUCCESS",
  INTERCITY_MY_BOOKINGS_FAILURE: "INTERCITY_MY_BOOKINGS_FAILURE",

  GET_ALL_INTERCITY_RIDE_REQUEST: "GET_ALL_INTERCITY_RIDE_REQUEST",
  GET_ALL_INTERCITY_RIDE_SUCCESS: "GET_ALL_INTERCITY_RIDE_SUCCESS",
  GET_ALL_INTERCITY_RIDE_FAILURE: "GET_ALL_INTERCITY_RIDE_FAILURE",

  GET_INTERCITY_DRIVER_RIDE_REQUEST: "GET_INTERCITY_DRIVER_RIDE_REQUEST",
  GET_INTERCITY_DRIVER_RIDE_SUCCESS: "GET_INTERCITY_DRIVER_RIDE_SUCCESS",
  GET_INTERCITY_DRIVER_RIDE_FAILURE: "GET_INTERCITY_DRIVER_RIDE_FAILURE",

  DRIVER_INTERCITY_RIDE_DETAILS_REQUEST:
    "DRIVER_INTERCITY_RIDE_DETAILS_REQUEST",
  DRIVER_INTERCITY_RIDE_DETAILS_SUCCESS:
    "DRIVER_INTERCITY_RIDE_DETAILS_SUCCESS",
  DRIVER_INTERCITY_RIDE_DETAILS_FAILURE:
    "DRIVER_INTERCITY_RIDE_DETAILS_FAILURE",

  CLEAR_RIDE_DETAILS_SUCCESS: "CLEAR_RIDE_DETAILS_SUCCESS",
  CLEAR_SEARCH_RIDE_DETAILS_SUCCESS: "CLEAR_RIDE_DETAILS_SUCCESS",

  BOOK_RIDE_REQUEST: "BOOK_RIDE_REQUEST",
  BOOK_RIDE_SUCCESS: "BOOK_RIDE_SUCCESS",
  BOOK_RIDE_FAILURE: "BOOK_RIDE_FAILURE",

  PAYMENT_INSERT_REQUEST: "PAYMENT_INSERT_REQUEST",
  PAYMENT_INSERT_SUCCESS: "PAYMENT_INSERT_SUCCESS",
  PAYMENT_INSERT_FAILURE: "PAYMENT_INSERT_FAILURE",

  MY_BOOKINGS_REQUEST: "MY_BOOKINGS_REQUEST",
  MY_BOOKINGS_SUCCESS: "MY_BOOKINGS_SUCCESS",
  MY_BOOKINGS_FAILURE: "MY_BOOKINGS_FAILURE",

  INTRACITY_RIDER_MY_BOOKINGS_REQUEST: "INTRACITY_RIDER_MY_BOOKINGS_REQUEST",
  INTRACITY_RIDER_MY_BOOKINGS_SUCCESS: "INTRACITY_RIDER_MY_BOOKINGS_SUCCESS",
  INTRACITY_RIDER_MY_BOOKINGS_FAILURE: "INTRACITY_RIDER_MY_BOOKINGS_FAILURE",

  INTRACITY_DRIVER_MY_BOOKINGS_REQUEST: "INTRACITY_DRIVER_MY_BOOKINGS_REQUEST",
  INTRACITY_DRIVER_MY_BOOKINGS_SUCCESS: "INTRACITY_DRIVER_MY_BOOKINGS_SUCCESS",
  INTRACITY_DRIVER_MY_BOOKINGS_FAILURE: "INTRACITY_DRIVER_MY_BOOKINGS_FAILURE",

  DRIVER_INTERCITY_MY_BOOKINGS_REQUEST: "DRIVER_INTERCITY_MY_BOOKINGS_REQUEST",
  DRIVER_INTERCITY_MY_BOOKINGS_SUCCESS: "DRIVER_INTERCITY_MY_BOOKINGS_SUCCESS",
  DRIVER_INTERCITY_MY_BOOKINGS_FAILURE: "DRIVER_INTERCITY_MY_BOOKINGS_FAILURE",

  DRIVER_CANCEL_BOOKING_REQUEST: "DRIVER_CANCEL_BOOKING_REQUEST",
  DRIVER_CANCEL_BOOKING_SUCCESS: "DRIVER_CANCEL_BOOKING_SUCCESS",
  DRIVER_CANCEL_BOOKING_FAILURE: "DRIVER_CANCEL_BOOKING_FAILURE",

  DRIVER_CANCEL_RIDE_REQUEST: "DRIVER_CANCEL_RIDE_REQUEST",
  DRIVER_CANCEL_RIDE_SUCCESS: "DRIVER_CANCEL_RIDE_SUCCESS",
  DRIVER_CANCEL_RIDE_FAILURE: "DRIVER_CANCEL_RIDE_FAILURE",

  DRIVER_INTERCITY_ALL_RIDE_CANCEL_REQUEST:
    "DRIVER_INTERCITY_ALL_RIDE_CANCEL_REQUEST",
  DRIVER_INTERCITY_ALL_RIDE_CANCEL_SUCCESS:
    "DRIVER_INTERCITY_ALL_RIDE_CANCEL_SUCCESS",
  DRIVER_INTERCITY_ALL_RIDE_CANCEL_FAILURE:
    "DRIVER_INTERCITY_ALL_RIDE_CANCEL_FAILURE",

  DRIVER_INTERCITY_CANCEL_RIDE_BEFORE_DEPARTURE_REQUEST:
    "DRIVER_INTERCITY_CANCEL_RIDE_BEFORE_DEPARTURE_REQUEST",
  DRIVER_INTERCITY_CANCEL_RIDE_BEFORE_DEPARTURE_SUCCESS:
    "DRIVER_INTERCITY_CANCEL_RIDE_BEFORE_DEPARTURE_SUCCESS",
  DRIVER_INTERCITY_CANCEL_RIDE_BEFORE_DEPARTURE_FAILURE:
    "DRIVER_INTERCITY_CANCEL_RIDE_BEFORE_DEPARTURE_FAILURE",

  RIDER_CANCEL_BOOKING_REQUEST: "RIDER_CANCEL_BOOKING_REQUEST",
  RIDER_CANCEL_BOOKING_SUCCESS: "RIDER_CANCEL_BOOKING_SUCCESS",
  RIDER_CANCEL_BOOKING_FAILURE: "RIDER_CANCEL_BOOKING_FAILURE",

  SAVE_RATING_REQUEST: "SAVE_RATING_REQUEST",
  SAVE_RATING_SUCCESS: "SAVE_RATING_SUCCESS",
  SAVE_RATING_FAILURE: "SAVE_RATING_FAILURE",

  SAVE_INTRACITY_RATING_REQUEST: "SAVE_INTRACITY_RATING_REQUEST",
  SAVE_INTRACITY_RATING_SUCCESS: "SAVE_INTRACITY_RATING_SUCCESS",
  SAVE_INTRACITY_RATING_FAILURE: "SAVE_INTRACITY_RATING_FAILURE",

  RIDE_BOOKING_DETAILS_REQUEST: "RIDE_BOOKING_DETAILS_REQUEST",
  RIDE_BOOKING_DETAILS_SUCCESS: "RIDE_BOOKING_DETAILS_SUCCESS",
  RIDE_BOOKING_DETAILS_FAILURE: "RIDE_BOOKING_DETAILS_FAILURE",

  UPDATE_RIDE_DETAILS_REQUEST: "UPDATE_RIDE_DETAILS_REQUEST",
  UPDATE_RIDE_DETAILS_SUCCESS: "UPDATE_RIDE_DETAILS_SUCCESS",
  UPDATE_RIDE_DETAILS_FAILURE: "UPDATE_RIDE_DETAILS_FAILURE",

  GET_POST_RIDE_DISTANCE_REQUEST: "GET_POST_RIDE_DISTANCE_REQUEST",
  GET_POST_RIDE_DISTANCE_SUCCESS: "GET_POST_RIDE_DISTANCE_SUCCESS",
  GET_POST_RIDE_DISTANCE_FAILURE: "GET_POST_RIDE_DISTANCE_FAILURE",

  INTERCITY_RIDE_BOOKING_DETAILS_REQUEST:
    "INTERCITY_RIDE_BOOKING_DETAILS_REQUEST",
  INTERCITY_RIDE_BOOKING_DETAILS_SUCCESS:
    "INTERCITY_RIDE_BOOKING_DETAILS_SUCCESS",
  INTERCITY_RIDE_BOOKING_DETAILS_FAILURE:
    "INTERCITY_RIDE_BOOKING_DETAILS_FAILURE",

  COMPLETE_RIDE_REQUEST: "COMPLETE_RIDE_REQUEST",
  COMPLETE_RIDE_SUCCESS: "COMPLETE_RIDE_SUCCESS",
  COMPLETE_RIDE_FAILURE: "COMPLETE_RIDE_FAILURE",

  UPDATE_SEAT_REQUEST: "UPDATE_SEAT_REQUEST",
  UPDATE_SEAT_SUCCESS: "UPDATE_SEAT_SUCCESS",
  UPDATE_SEAT_FAILURE: "UPDATE_SEAT_FAILURE",

  GET_REVIEWS_DETAIL_REQUEST: "GET_REVIEWS_DETAIL_REQUEST",
  GET_REVIEWS_DETAIL_SUCCESS: "GET_REVIEWS_DETAIL_SUCCESS",
  GET_REVIEWS_DETAIL_FAILURE: "GET_REVIEWS_DETAIL_FAILURE",

  IS_ONLINE_REQUEST: "IS_ONLINE_REQUEST",
  IS_ONLINE_SUCCESS: "IS_ONLINE_SUCCESS",
  IS_ONLINE_FAILURE: "IS_ONLINE_FAILURE",

  DRIVER_DETAILS_REQUEST: "DRIVER_DETAILS_REQUEST",
  DRIVER_DETAILS_SUCCESS: "DRIVER_DETAILS_SUCCESS",
  DRIVER_DETAILS_FAILURE: "DRIVER_DETAILS_FAILURE",

  UPDATE_DRIVER_REQUEST: "UPDATE_DRIVER_REQUEST",
  UPDATE_DRIVER_SUCCESS: "UPDATE_DRIVER_SUCCESS",
  UPDATE_DRIVER_FAILURE: "UPDATE_DRIVER_FAILURE",

  CHANGE_ROLE_REQUEST: "CHANGE_ROLE_REQUEST",
  CHANGE_ROLE_SUCCESS: "CHANGE_ROLE_SUCCESS",
  CHANGE_ROLE_FAILURE: "CHANGE_ROLE_FAILURE",

  ADD_INTERCITY_RIDE_REQUEST: "ADD_INTERCITY_RIDE_REQUEST",
  ADD_INTERCITY_RIDE_SUCCESS: "ADD_INTERCITY_RIDE_SUCCESS",
  ADD_INTERCITY_RIDE_FAILURE: "ADD_INTERCITY_RIDE_FAILURE",

  ADD_INTRACITY_RIDE_REQUEST: "ADD_INTRACITY_RIDE_REQUEST",
  ADD_INTRACITY_RIDE_SUCCESS: "ADD_INTRACITY_RIDE_SUCCESS",
  ADD_INTRACITY_RIDE_FAILURE: "ADD_INTRACITY_RIDE_FAILURE",

  CHECK_AVAILABLE_CITY_REQUEST: "CHECK_AVAILABLE_CITY_REQUEST",
  CHECK_AVAILABLE_CITY_SUCCESS: "CHECK_AVAILABLE_CITY_SUCCESS",
  CHECK_AVAILABLE_CITY_FAILURE: "CHECK_AVAILABLE_CITY_FAILURE",

  GET_DRIVER_DETAILS_REQUEST: "GET_DRIVER_DETAILS_REQUEST",
  GET_DRIVER_DETAILS_SUCCESS: "GET_DRIVER_DETAILS_SUCCESS",
  GET_DRIVER_DETAILS_FAILURE: "GET_DRIVER_DETAILS_FAILURE",

  DELETE_DRIVER_MEDIA_REQUEST: "DELETE_DRIVER_MEDIA_REQUEST",
  DELETE_DRIVER_MEDIA_SUCCESS: "DELETE_DRIVER_MEDIA_SUCCESS",
  DELETE_DRIVER_MEDIA_FAILURE: "DELETE_DRIVER_MEDIA_FAILURE",

  GET_INTRACITY_RIDER_RIDE_REQUEST: "GET_INTRACITY_RIDER_RIDE_REQUEST",
  GET_INTRACITY_RIDER_RIDE_SUCCESS: "GET_INTRACITY_RIDER_RIDE_SUCCESS",
  GET_INTRACITY_RIDER_RIDE_FAILURE: "GET_INTRACITY_RIDER_RIDE_FAILURE",

  GET_INTRACITY_DRIVER_RIDE_REQUEST: "GET_INTRACITY_DRIVER_RIDE_REQUEST",
  GET_INTRACITY_DRIVER_RIDE_SUCCESS: "GET_INTRACITY_DRIVER_RIDE_SUCCESS",
  GET_INTRACITY_DRIVER_RIDE_FAILURE: "GET_INTRACITY_DRIVER_RIDE_FAILURE",

  DRIVER_INTRACITY_ADD_LOCATION_REQUEST:
    "DRIVER_INTRACITY_ADD_LOCATION_REQUEST",
  DRIVER_INTRACITY_ADD_LOCATION_SUCCESS:
    "DRIVER_INTRACITY_ADD_LOCATION_SUCCESS",
  DRIVER_INTRACITY_ADD_LOCATION_FAILURE:
    "DRIVER_INTRACITY_ADD_LOCATION_FAILURE",

  INTRACITY_RIDE_DETAILS_REQUEST: "INTRACITY_RIDE_DETAILS_REQUEST",
  INTRACITY_RIDE_DETAILS_SUCCESS: "INTRACITY_RIDE_DETAILS_SUCCESS",
  INTRACITY_RIDE_DETAILS_FAILURE: "INTRACITY_RIDE_DETAILS_FAILURE",

  INTRACITY_CANCEL_RIDE_REQUEST: "INTRACITY_CANCEL_RIDE_REQUEST",
  INTRACITY_CANCEL_RIDE_SUCCESS: "INTRACITY_CANCEL_RIDE_SUCCESS",
  INTRACITY_CANCEL_RIDE_FAILURE: "INTRACITY_CANCEL_RIDE_FAILURE",

  INTRACITY_ACCEPT_RIDE_REQUEST: "INTRACITY_ACCEPT_RIDE_REQUEST",
  INTRACITY_ACCEPT_RIDE_SUCCESS: "INTRACITY_ACCEPT_RIDE_SUCCESS",
  INTRACITY_ACCEPT_RIDE_FAILURE: "INTRACITY_ACCEPT_RIDE_FAILURE",

  INTRACITY_START_RIDE_REQUEST: "INTRACITY_START_RIDE_REQUEST",
  INTRACITY_START_RIDE_SUCCESS: "INTRACITY_START_RIDE_SUCCESS",
  INTRACITY_START_RIDE_FAILURE: "INTRACITY_START_RIDE_FAILURE",

  INTRACITY_COMPLETE_RIDE_REQUEST: "INTRACITY_COMPLETE_RIDE_REQUEST",
  INTRACITY_COMPLETE_RIDE_SUCCESS: "INTRACITY_COMPLETE_RIDE_SUCCESS",
  INTRACITY_COMPLETE_RIDE_FAILURE: "INTRACITY_COMPLETE_RIDE_FAILURE",

  EMAIL_US_REQUEST: "EMAIL_US_REQUEST",
  EMAIL_US_SUCCESS: "EMAIL_US_SUCCESS",
  EMAIL_US_FAILURE: "EMAIL_US_FAILURE",

  CHANGE_LANGUAGE_REQUEST: "CHANGE_LANGUAGE_REQUEST",
  CHANGE_LANGUAGE_SUCCESS: "CHANGE_LANGUAGE_SUCCESS",
  CHANGE_LANGUAGE_FAILURE: "CHANGE_LANGUAGE_FAILURE",

  REFERRAL_CODE_REQUEST: "REFERRAL_CODE_REQUEST",
  REFERRAL_CODE_SUCCESS: "REFERRAL_CODE_SUCCESS",
  REFERRAL_CODE_FAILURE: "REFERRAL_CODE_FAILURE",

  INTERCITY_PAYMENT_REQUEST: "INTERCITY_PAYMENT_REQUEST",
  INTERCITY_PAYMENT_SUCCESS: "INTERCITY_PAYMENT_SUCCESS",
  INTERCITY_PAYMENT_FAILURE: "INTERCITY_PAYMENT_FAILURE",

  TOTAL_REVENUE_REQUEST: "TOTAL_REVENUE_REQUEST",
  TOTAL_REVENUE_SUCCESS: "TOTAL_REVENUE_SUCCESS",
  TOTAL_REVENUE_FAILURE: "TOTAL_REVENUE_FAILURE",

  WITHDRAW_BALANCE_REQUEST: "WITHDRAW_BALANCE_REQUEST",
  WITHDRAW_BALANCE_SUCCESS: "WITHDRAW_BALANCE_SUCCESS",
  WITHDRAW_BALANCE_FAILURE: "WITHDRAW_BALANCE_FAILURE",

  INTERCITY_REVENUE_REQUEST: "INTERCITY_REVENUE_REQUEST",
  INTERCITY_REVENUE_SUCCESS: "INTERCITY_REVENUE_SUCCESS",
  INTERCITY_REVENUE_FAILURE: "INTERCITY_REVENUE_FAILURE",

  INTRACITY_REVENUE_REQUEST: "INTRACITY_REVENUE_REQUEST",
  INTRACITY_REVENUE_SUCCESS: "INTRACITY_REVENUE_SUCCESS",
  INTRACITY_REVENUE_FAILURE: "INTRACITY_REVENUE_FAILURE",

  GET_DRIVER_SUB_REQUEST: "GET_DRIVER_SUB_REQUEST",
  GET_DRIVER_SUB_SUCCESS: "GET_DRIVER_SUB_SUCCESS",
  GET_DRIVER_SUB_FAILURE: "GET_DRIVER_SUB_FAILURE",

  ADD_SUBSCRIPTION_REQUEST: "ADD_SUBSCRIPTION_REQUEST",
  ADD_SUBSCRIPTION_SUCCESS: "ADD_SUBSCRIPTION_SUCCESS",
  ADD_SUBSCRIPTION_FAILURE: "ADD_SUBSCRIPTION_FAILURE",

  SUBSCRIPTION_PAYMENT_REQUEST: "SUBSCRIPTION_PAYMENT_REQUEST",
  SUBSCRIPTION_PAYMENT_SUCCESS: "SUBSCRIPTION_PAYMENT_SUCCESS",
  SUBSCRIPTION_PAYMENT_FAILURE: "SUBSCRIPTION_PAYMENT_FAILURE",

  SUBSCRIPTION_DETAILS_REQUEST: "SUBSCRIPTION_DETAILS_REQUEST",
  SUBSCRIPTION_DETAILS_SUCCESS: "SUBSCRIPTION_DETAILS_SUCCESS",
  SUBSCRIPTION_DETAILS_FAILURE: "SUBSCRIPTION_DETAILS_FAILURE",

  SUBSCRIPTION_CANCEL_REQUEST: "SUBSCRIPTION_CANCEL_REQUEST",
  SUBSCRIPTION_CANCEL_SUCCESS: "SUBSCRIPTION_CANCEL_SUCCESS",
  SUBSCRIPTION_CANCEL_FAILURE: "SUBSCRIPTION_CANCEL_FAILURE",

  ADD_GET_PAID_ACC_REQUEST: "ADD_GET_PAID_ACC_REQUEST",
  ADD_GET_PAID_ACC_SUCCESS: "ADD_GET_PAID_ACC_SUCCESS",
  ADD_GET_PAID_ACC_FAILURE: "ADD_GET_PAID_ACC_FAILURE",

  GET_PAID_ACC_DETAILS_REQUEST: "GET_PAID_ACC_DETAILS_REQUEST",
  GET_PAID_ACC_DETAILS_SUCCESS: "GET_PAID_ACC_DETAILS_SUCCESS",
  GET_PAID_ACC_DETAILS_FAILURE: "GET_PAID_ACC_DETAILS_FAILURE",

  UPDATE_GET_PAID_ACC_DETAILS_REQUEST: "UPDATE_GET_PAID_ACC_DETAILS_REQUEST",
  UPDATE_GET_PAID_ACC_DETAILS_SUCCESS: "UPDATE_GET_PAID_ACC_DETAILS_SUCCESS",
  UPDATE_GET_PAID_ACC_DETAILS_FAILURE: "UPDATE_GET_PAID_ACC_DETAILS_FAILURE",

  UPDATE_BANK_ACC_DETAILS_REQUEST: "UPDATE_BANK_ACC_DETAILS_REQUEST",
  UPDATE_BANK_ACC_DETAILS_SUCCESS: "UPDATE_BANK_ACC_DETAILS_SUCCESS",
  UPDATE_BANK_ACC_DETAILS_FAILURE: "UPDATE_BANK_ACC_DETAILS_FAILURE",

  CHANGE_PAYOUT_STATUS_REQUEST: "CHANGE_PAYOUT_STATUS_REQUEST",
  CHANGE_PAYOUT_STATUS_SUCCESS: "CHANGE_PAYOUT_STATUS_SUCCESS",
  CHANGE_PAYOUT_STATUS_FAILURE: "CHANGE_PAYOUT_STATUS_FAILURE",

  CLEAR_INTRACITY_RIDE_DETAILS_SUCCESS: "CLEAR_INTRACITY_RIDE_DETAILS_SUCCESS",

  IS_FROM_ROOT: "IS_FROM_ROOT",

  DEFAULT_API_FAILURE: "DEFAULT_API_FAILURE",
};
